name: Edicola

on:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Refresh
       run: 'curl -s -H "Token: $EDICOLA_TOKEN" -X POST $EDICOLA_ENDPOINT/refreshEdicola'
       env:
        EDICOLA_TOKEN: ${{ secrets.EDICOLA_TOKEN }}
        EDICOLA_ENDPOINT: ${{ secrets.EDICOLA_ENDPOINT }}